### ISSUE TITLE
python prepare.py fails

### ISSUE THREAD

**Issue by opoplawski** [trelau/SMESH#35]
# Issue description

Trying to run python prepare.py from current git master on Fedora rawhide:

```
$ python prepare.py
Traceback (most recent call last):
  File "/home/orion/fedora/smesh/SMESH-ab0f4357a2fc8c250102bbf9ff2e057a9ca6a1aa/prepare.py", line 119, in <module>
    prepare_netgen()
  File "/home/orion/fedora/smesh/SMESH-ab0f4357a2fc8c250102bbf9ff2e057a9ca6a1aa/prepare.py", line 21, in prepare_netgen
    pset = patch.fromfile('external/NETGENPlugin/src/NETGEN/netgen53ForSalome.patch')
AttributeError: module 'patch' has no attribute 'fromfile'
```

**Comment by opoplawski** [comment]
Appears to work if I install the patch module with pip.  Probably worth a mention.

**Comment by trelau** [comment]
Added note in readme about installing patch.py in https://github.com/trelau/SMESH/pull/42
