### ISSUE TITLE
trying to compile latest sources fails with:

### ISSUE THREAD

**Issue by looooo** [trelau/SMESH#67]
```
branch 'int_32_test' set up to track 'origin/int_32_test'.
Traceback (most recent call last):
  File "/Users/lo/mambaforge/conda-bld/smesh_1657122221167/work/SMESH/prepare.py", line 185, in <module>
    prepare_netgen()
  File "/Users/lo/mambaforge/conda-bld/smesh_1657122221167/work/SMESH/prepare.py", line 20, in prepare_netgen
    pset = patch.fromfile('external/NETGENPlugin/src/NETGEN/netgen62ForSalome.patch')
  File "/Users/lo/mambaforge/conda-bld/smesh_1657122221167/_build_env/lib/python3.9/site-packages/patch.py", line 167, in fromfile
    fp = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'external/NETGENPlugin/src/NETGEN/netgen62ForSalome.patch'
Traceback (most recent call last):
  File "/Users/lo/mambaforge/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/lo/mambaforge/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 488, in main
    execute(sys.argv[1:])
  File "/Users/lo/mambaforge/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 477, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/Users/lo/mambaforge/lib/python3.10/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/lo/mambaforge/lib/python3.10/site-packages/conda_build/build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/lo/mambaforge/lib/python3.10/site-packages/conda_build/build.py", line 2211, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/lo/mambaforge/lib/python3.10/site-packages/conda_build/utils.py", line 411, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/lo/mambaforge/lib/python3.10/site-packages/conda_build/utils.py", line 391, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
```

not sure what I did wrong. Can we do a ci-run to see if everything is still working? @trelau

**Comment by looooo** [comment]
I used wrong submodules.
