### ISSUE TITLE
D:\python\python.exe D:\salome-smesh\SMESH\prepare.py  Traceback (most recent call last):   File "D:\salome-smesh\SMESH\prepare.py", line 189, in <module>     prepare_netgen()   File "D:\salome-smesh\SMESH\prepare.py", line 22, in prepare_netgen     raise RuntimeError('Failed to apply Netgen patch.') RuntimeError: Failed to apply Netgen patch.  Process finished with exit code 1

### ISSUE THREAD

**Issue by wrxhardworking** [trelau/SMESH#78]
# Issue description

(Provide a short description, state the expected behavior and what actually happens.)

# Reproducible example code

(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete snippets that can be easily compiled and run to diagnose the issue.)

**Comment by wrxhardworking** [comment]
prepare.py have a problem
